export const playerBlock: string;
export const musicBlock: string;
export const topBlock: string;
export const musicName: string;
export const bottomBlock: string;
export const playerControllerBlock: string;
export const icon: string;
export const playStatusIcon: string;
export const soundBlock: string;
