export const listIcon: string;
export const listBlock: string;
export const listLeftBlock: string;
export const musicListImg: string;
export const musicListIndex: string;
export const listRightBlock: string;
export const floatList: string;
export const currentPlatIcon: string;
export const shadow: string;
